language: python
sudo: false
python:
 - "3.6"

install:
 - "pip install -r requirements.txt"
 - "pip install ."

script:
  - "pytest --cov {{ cookiecutter.repo_name }} --cov-report term-missing tests/"

notifications:
  email:
    on_success: change
on_failure: always