version: "3.4"
services:
  fc-alchemist:
    build: .
    network_mode: "host"
    environment:
      - SQS_QUEUE=alchemist-standard
      - SQS_TIMEOUT_SEC=500
      - MAKE_PUBLIC=True

      - AWS_ACCESS_KEY_ID=${ODC_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${ODC_SECRET_KEY}
      - AWS_DEFAULT_REGION=us-west-2
      - DATACUBE_CONFIG_PATH=/opt/custom-config.conf
      - DB_DATABASE=opendatacube
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_PORT=5432
      - DB_HOSTNAME=172.19.0.3
    volumes:
      - ./data:/opt/data
      - ./Docker:/opt/scripts