specification:
  product: usgs_ls8c_level2_2
  measurements: ['b2', 'b3', 'b4', 'b5', 'b6', 'b7']
  measurement_renames:
    b2: blue
    b3: green
    b4: red
    b5: nir
    b6: swir1
    b7: swir2

  transform: fc.virtualproduct.FractionalCover
  transform_args:
    regression_coefficients:
      blue:
        - 0.00041
        - 0.97470
      green:
        - 0.00289
        - 0.99779
      red:
        - 0.00274
        - 1.00446
      nir:
        - 0.00004
        - 0.98906
      swir1:
        - 0.00256
        - 0.99467
      swir2:
        - -0.00327
        - 1.02551
  override_product_family: ard # The relationship of the source dataset to the newly derived dataset

output:
  #location: '/g/data/u46/users/dsg547/sandpit/odc_testing/aws_fc_testing'
  location: 's3://test-results-deafrica-staging-west/fc-alchemist-testsII'
  dtype: uint8 # single value for all bands
  nodata: 255 # single value for all bands
  preview_image: [pv, npv, bs]

  metadata: # metadata are settings available on DatasetAssembler
    product_family: fractional_cover
    producer: ga.gov.au
    dataset_version: 2.0.0
  properties: # Properties can be anything and everything
    dea:dataset_maturity: interim

processing:
  dask_chunks:
    x: 1000
    y: 1000
