specification:
  product: ga_s2a_ard_nbar_granule
  measurements: ['nbar_green', 'nbar_red', 'nbar_nir_1', 'nbar_swir_2', 'nbar_swir_3']
  measurement_renames:
    nbar_green: green
    nbar_red: red
    nbar_nir_1: nir
    nbar_swir_2: swir1
    nbar_swir_3: swir2
  # For africa data
  #  product: ls5_usgs_sr_scene
  #  measurements: ['green', 'red', 'nir', 'swir1', 'swir2']

  override_product_family: ard # The relationship of the source dataset to the newly derived dataset

  transform: fc.virtualproduct.FakeFractionalCover
  transform_args:
    regression_coefficients:
      blue:
        - 0.00041
        - 0.97470
      green:
        - 0.00289
        - 0.99779
      red:
        - 0.00274
        - 1.00446
      nir:
        - 0.00004
        - 0.98906
      swir1:
        - 0.00256
        - 0.99467
      swir2:
        - -0.00327
        - 1.02551



output:
  #location: 's3://test-results-deafrica-staging-west/fc-alchemist-tests'
  #location: '/g/data/u46/users/dsg547/test_data'
  location: '/home/osboxes/test_data'
  dtype: uint8 # single value for all bands
  nodata: 255 # single value for all bands
  preview_image: [pv, npv, bs]

#  reference_source_dataset: False
  metadata: # metadata are settings available on DatasetAssembler
    product_family: fractional_cover
    producer: ga.gov.au
    dataset_version: 2.0.0
  properties: # Properties can be anything and everything
    dea:dataset_maturity: interim

processing:
  dask_chunks:
    x: 1000
    y: 1000

