name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'datacube_alchemist/**'
      - 'tests/**'
      - '.github/workflows/test.yml'

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build the docker container
      run: |
        docker-compose build

    - name: Initialise datacube database
      run: |
        docker-compose run alchemist datacube system init
        docker-compose run alchemist datacube-alchemist --version

    - name: Run linting
      run: |
        docker-compose run alchemist datacube-alchemist --version
        docker-compose run alchemist black --check datacube_alchemist

    - name: Run tests
      run: |
        docker-compose run alchemist bash -c "pip freeze; pip install .; pip freeze; pytest tests"

    - name: Integration tests
      run: |
        docker-compose run alchemist bash ./tests/integration_tests.sh
